"""Structured content for the templated pages: six solutions, six industries, resources, news, careers.

Everything a solution or industry page says lives here, so the pages share one structure
(hero, impact figures, applications, deep dives, industries, resources, FAQ) and one vocabulary.
Copy rules: outcomes and guarantees, never mechanism; the company speaks, no people; every number
comes from build.FACTS or a cited source; say each thing once.
"""

# ------------------------------------------------------------------ resources (brief, explainers, posts)
RESOURCES = {
    "brief": {"type": "Technical brief", "title": "Fluid Silicon technical brief", "path": "/assets/docs/fluid-silicon-technical-brief.pdf",
              "desc": "Six pages: the problem, the platform, adoption, security and integration, device support.",
              "thumb": "brief"},
    "margin": {"type": "Blog", "title": "The FPGA margin problem", "path": "/blog/the-fpga-margin-problem/",
               "desc": "Why timing models carry 30–54% margin for the worst chip in the population, why that was the right call, and what per-chip measurement changes.", "thumb": "margin"},
    "aging": {"type": "Blog", "title": "Aging is measurable, in the field", "path": "/blog/aging-is-measurable/",
              "desc": "Temperature sets the aging rate. The same board reaches its threshold years apart in a cool rack and a hot enclosure, and now that can be measured.", "thumb": "aging"},
    "generations": {"type": "Blog", "title": "Five board generations, one health metric", "path": "/blog/one-health-metric-many-generations/",
                    "desc": "What mixed-vendor, multi-generation fleets need from telemetry: one number that means one thing on every part.", "thumb": "fleet"},
    "power": {"type": "Blog", "title": "What a point of card power is worth", "path": "/blog/what-a-point-of-power-is-worth/",
              "desc": "A worked example for 10,000 cards: the arithmetic behind adaptive voltage scaling at fleet scale.", "thumb": "power"},
    "readonly": {"type": "Blog", "title": "Read-only first: how an evaluation runs", "path": "/blog/read-only-first/",
                 "desc": "Evaluate, observe, optimize, repair: four opt-in steps, and what each needs from your team.", "thumb": "steps"},
    "security": {"type": "Explainer", "title": "Security and integration", "path": "/technology/security/",
                 "desc": "Where the health layer sits, what moves in each direction, and its six guarantees.", "thumb": "shield"},
    "devices": {"type": "Explainer", "title": "Device support", "path": "/technology/devices/",
                "desc": "AMD and Altera families, and the status of each.", "thumb": "chip"},
}

# ------------------------------------------------------------------ news and company updates
NEWS = [
    {"date": "2026-09-24", "label": "September 2026", "title": "Fluid Silicon publishes its technical brief",
     "excerpt": "Six pages on the problem, the platform, adoption, security and integration, and device support.",
     "path": "/assets/docs/fluid-silicon-technical-brief.pdf", "source": "Fluid Silicon", "kind": "update"},
    {"date": "2026-05-05", "label": "May 2026", "title": "Penn Today: a way for computer chips to run more efficiently",
     "excerpt": "The University of Pennsylvania on the research behind Fluid Silicon and the President's Sustainability Prize awarded to Nhlanhla Mavuso for the project.",
     "path": "https://penntoday.upenn.edu/news/penn-student-develops-way-computer-chips-run-more-efficiently", "source": "Penn Today", "kind": "press"},
    {"date": "2026-04-16", "label": "April 2026", "title": "Nhlanhla Mavuso awarded Penn's President's Sustainability Prize for Fluid Silicon",
     "excerpt": "Penn announces its 2026 prize recipients. The Sustainability Prize recognizes the work behind Fluid Silicon: running chips at their measured limits instead of a worst-case margin.",
     "path": "https://penntoday.upenn.edu/news/class-2026-presidents-engagement-and-innovation-prize-winners-announced", "source": "Penn Today", "kind": "award"},
]

# ------------------------------------------------------------------ solutions (by topic)
SOLUTIONS = [
    {
        "slug": "reliability-availability-serviceability", "problem": ('Paths fail in service without warning', 'A path that closed timing at sign-off slows with temperature and aging until it violates setup in the field. A time-to-threshold per element schedules the fix before it fails.'), "name": "Reliability, Availability, Serviceability", "icon": "shield",
        "short": "Predict timing failures and fix them in a window you choose.",
        "lead": "A card that fails without warning takes capacity with it and sends errors downstream. Fluid Silicon watches the timing health of every logic element, predicts when each card will cross your threshold, and, only where an element is degrading, repairs it in a window you choose.",
        "impact": [("1 s", "to sweep every logic element while the design runs"),
                   ("< 1%", "of LUTs, and under 5% of flip-flops, on a production shell"),
                   ("0", "downtime to monitor")],
        "apps": [
            ("monitor", "monitor", "Health Monitoring", "Per-element timing slack, measured at speed, on every card."),
            ("model", "model", "Aging Models", "An aging curve per card, fitted to its temperature history, with a time-to-threshold."),
            ("alerts", "flag", "Alerts & Thresholds", "Watch, action and repair states on thresholds you set."),
            ("repair", "repair", "Repair", "When an element degrades toward your threshold, its path moves to a healthy resource, through your change process."),
        ],
        "dives": [
            {"id": "monitor", "kicker": "Health Monitoring", "title": "Every element, every card, about once a second.",
             "bullets": ["Timing slack on individual LUTs, carry blocks and the links between them.",
                         "At operating speed, while the design computes.",
                         "One metric on every vendor: measured slack as a share of the clock period.",
                         "One telemetry schema, into your existing monitoring."],
             "visual": "mock_light:fleet|Fleet overview with healthy, watch and action counts. Illustrative screen.",
             "sub": ("Attribution", "Without per-element visibility a failure has no cause. Measurement gives each card a record: what it sustains today, how fast it is changing, and when it needs attention."),
             "cta": ("Request a demo", "/demo/")},
            {"id": "model", "kicker": "Aging Models", "title": "A time-to-threshold for every card.",
             "bullets": ["Each element tracked for the life of the card.",
                         "Aging fitted to the card's own temperature history.",
                         "A predicted date for crossing your alert threshold.",
                         "Outliers flagged months ahead."],
             "visual": "aging_c:aging-ras",
             "sub": ("Hotter enclosures age faster", "Negative bias temperature instability and related mechanisms slow logic over time, faster at high temperature and voltage. Identical boards in different racks reach the threshold years apart."),
             "cta": ("Read the aging explainer", "/blog/aging-is-measurable/")},
            {"id": "alerts", "kicker": "Alerts & Thresholds", "title": "Your thresholds. Your windows.",
             "bullets": ["Watch, action and repair thresholds per fleet or per family.",
                         "Alerts name the card, the element and the predicted time-to-threshold.",
                         "Recommendations wait for approval.",
                         "Reports for capacity and replacement planning."],
             "visual": "mock_light:card|A card past the action threshold, with the recommended repair window awaiting approval. Illustrative screen.",
             "sub": ("Nothing changes without you", "Read-only is the default. Tuning and repair are enabled separately and run only in maintenance windows you schedule."),
             "cta": ("Security and integration", "/technology/security/")},
            {"id": "repair", "kicker": "Repair", "title": "Move only what is degrading.",
             "bullets": ["Nothing in your design moves until an element degrades toward your threshold.",
                         "Then only that path is moved to a healthy resource, in your maintenance window, through your change process.",
                         "The repaired card is re-measured within a second.",
                         "Everything else on the card stays exactly as built."],
             "visual": "illus:illus-ras",
             "sub": ("Serviceability without a truck roll", "A card that would have been replaced is repaired in place and kept in service, with the measurements to show it is healthy."),
             "cta": ("How the platform works", "/technology/")},
        ],
        "resources": ["aging", "generations", "brief"],
        "faq": [
            ("What counts as a failure here?", "A logic element whose measured slack falls below the threshold you set. Fluid Silicon addresses timing variation and wear-out; it complements radiation mitigation and other fault-tolerance measures rather than replacing them."),
            ("Do we need downtime to monitor?", "No. The design keeps computing for the whole measurement, and a full sweep of every logic element takes about a second."),
            ("How early is the warning?", "The aging model projects when each card crosses your threshold, typically months to years ahead, so replacements and repairs are planned rather than reactive."),
            ("What happens when a card reaches a threshold?", "An alert names the card, the element and the forecast, with a recommended action. The action runs only after your approval, in a window you schedule."),
            ("Does repair change our design?", "Not until something needs it. Your logic, routing and I/O stay as built. If an element degrades toward your threshold, repair moves only the affected path to a healthy resource, in your window and through your change process. Everything else stays as built."),
            ("Which vendors and nodes?", "AMD and Altera families from 28 nm to 10 nm class today; 14 nm and 7 nm families in development. See device support."),
            ("Where does the telemetry go?", "Into your existing monitoring, in one vendor-neutral schema. The platform is deployed on your site; nothing leaves your network."),
            ("Can we keep it read-only?", "Yes, indefinitely. Monitoring and modeling are read-only; tuning and repair are steps you choose to enable."),
        ],
    },
    {
        "slug": "failure-prediction-diagnostics", "problem": ('Intermittent errors that never reproduce', 'Errors that disappear on the bench close as no fault found. Measured slack per LUT and carry chain gives every error a location on the die.'), "name": "Failure Prediction & Diagnostics", "icon": "search",
        "short": "Give every error an address, a history and a forecast.",
        "lead": "When a card fails today, nobody can say which logic caused it. Fluid Silicon measures every element, so a fault has an address, a history and a forecast.",
        "impact": [("< 20 ps", "per-link measurement precision"),
                   ("> 20%", "random variation at 16, 14 and 7 nm: why identical cards fail differently"),
                   ("6+ years", "cards now stay in service, beyond what their timing models assumed")],
        "apps": [
            ("predict", "model", "Degradation Prediction", "A forecast per card and per element, from measured history."),
            ("attribute", "search", "Error Attribution", "An error tied to the element that caused it, with the measurements to prove it."),
            ("outliers", "variation", "Outlier Detection", "The cards and elements far from the rest of the fleet, before they fail."),
            ("evidence", "doc", "Evidence for Root Cause", "Per-element history for your reliability engineers and your vendors."),
        ],
        "dives": [
            {"id": "predict", "kicker": "Degradation Prediction", "title": "Which card fails next, and when.",
             "bullets": ["Every element measured about once a second for the life of the card.",
                         "A per-card aging curve fitted to its temperature history.",
                         "A time-to-threshold that feeds replacement and capacity planning.",
                         "Cards aging faster than their neighbours flagged early."],
             "visual": "aging_c:aging-fpd",
             "sub": ("Prediction, not a schedule", "Replacing boards on a fixed schedule retires healthy cards and misses failing ones. A forecast per card replaces the schedule."),
             "cta": ("Request a demo", "/demo/")},
            {"id": "attribute", "kicker": "Error Attribution", "title": "A fault with an address.",
             "bullets": ["Per-element slack history around the time of an error.",
                         "The weakest element on the card, and how long it has been weakening.",
                         "Evidence that separates a timing fault from a software or thermal event.",
                         "Reports your reliability team can attach to a ticket."],
             "visual": "mock_light:card|One card's health with its weakest element and history. Illustrative screen.",
             "sub": ("Before the error travels", "An error in one card can take capacity offline or propagate downstream. Attribution shortens the path from symptom to cause."),
             "cta": ("Security and integration", "/technology/security/")},
            {"id": "outliers", "kicker": "Outlier Detection", "title": "The tails of the fleet.",
             "bullets": ["Each card's weakest element compared across the fleet.",
                         "Systematic and random variation separated from aging.",
                         "Cards far below the family median surfaced first.",
                         "The same comparison on AMD and Altera parts."],
             "visual": "margin_half:margin-fpd",
             "sub": ("Variation at scale", "At 16, 14 and 7 nm, random variation alone exceeds 20%, on top of systematic variation across the die. Measuring more chips finds more tails."),
             "cta": ("Read the margin explainer", "/blog/the-fpga-margin-problem/")},
            {"id": "evidence", "kicker": "Evidence for Root Cause", "title": "Data your vendors can act on.",
             "bullets": ["Per-element measurements from the day a card entered service.",
                         "Temperature and operating-point history alongside timing.",
                         "Exit characterization when a card leaves service.",
                         "One vendor-neutral format for your team and your suppliers."],
             "visual": "illus:illus-fpd",
             "sub": ("Feedback to the silicon vendor", "A card returned with a measured history is a different conversation from a card returned with a symptom."),
             "cta": ("Technical brief (PDF)", "/assets/docs/fluid-silicon-technical-brief.pdf")},
        ],
        "resources": ["aging", "margin", "brief"],
        "faq": [
            ("What kinds of failure does this predict?", "Timing failures from variation and wear-out: logic that has slowed past its margin. It does not predict mechanical, power-supply or radiation events; it complements the measures you have for those."),
            ("How is an error attributed?", "Every logic element has a measured slack history, so an error is checked against the elements that were weakest at the time. The result is evidence, not inference."),
            ("Can it tell aging from a bad batch?", "Yes. Aging shows as a trend in a card's own history; a bad batch shows as an outlier at incoming characterization, before the card ages at all."),
            ("Does monitoring affect our design's timing?", "The health layer adds under 2% delay and occupies under 1% of LUTs on a production shell. It does not interfere with the design's computation."),
            ("How often is each card measured?", "A full sweep of every logic element takes about a second and runs while the design computes. The interval between sweeps is yours to set."),
            ("Which devices are supported?", "AMD 7-series, UltraScale and UltraScale+ today, with select Altera Agilex 7 devices; more families in development. See device support."),
        ],
    },
    {
        "slug": "card-qualification", "problem": ('Incoming boards of unknown margin', 'Same part number, same speed grade, different silicon. Measure every board at incoming inspection and know which ones sit near their timing limit.'), "name": "Card Qualification", "icon": "check",
        "short": "Measure every board's margin at incoming inspection.",
        "lead": "Two cards with the same part number are not the same card. Fluid Silicon characterizes every LUT and carry block at speed before a card enters service: how much margin it has and where it is weak.",
        "impact": [("1 s", "to characterize every logic element of a card"),
                   ("> 20%", "random variation at 16, 14 and 7 nm, on top of systematic variation across the die"),
                   ("< 20 ps", "per-link measurement precision")],
        "apps": [
            ("incoming", "chip", "Incoming Characterization", "Every card measured at speed on arrival, read-only."),
            ("maps", "layers", "Weak-Resource Maps", "Where each chip is slow, so your next build can avoid it."),
            ("binning", "variation", "Margin-Based Binning", "Cards sorted by measured margin, not part number."),
            ("evidence", "doc", "Acceptance Evidence", "A per-card timing and variation report for acceptance, warranty and resale."),
        ],
        "dives": [
            {"id": "incoming", "kicker": "Incoming Characterization", "title": "Measure it before you trust it.",
             "bullets": ["Every LUT and carry block measured at speed, about a second per card.",
                         "A per-card timing and variation report.",
                         "Tail cards identified on day one.",
                         "The same report on AMD and Altera parts."],
             "visual": "illus:illus-cq",
             "sub": ("Where evaluations start", "A sample of your cards in staging, a report per card, no change to any operating point."),
             "cta": ("Request a demo", "/demo/")},
            {"id": "maps", "kicker": "Weak-Resource Maps", "title": "Know where each chip is weak.",
             "bullets": ["Measured slack mapped across the chip's logic elements.",
                         "Random, systematic and spatial variation shown separately.",
                         "Guidance for your next place-and-route, so critical paths avoid weak regions. Your current build is not touched.",
                         "Re-measured for the life of the card."],
             "visual": "mock_light:card|Slack across every element of one card, with its weakest element. Illustrative screen.",
             "sub": ("Spatial variation", "Neighbouring resources drift together, so one weak region can hold several critical paths."),
             "cta": ("How the platform works", "/technology/")},
            {"id": "binning", "kicker": "Margin-Based Binning", "title": "Sort cards by what they measured.",
             "bullets": ["Cards binned by measured margin at their operating point.",
                         "The fastest cards matched to the workloads that need them.",
                         "Cards near the threshold kept out of critical roles.",
                         "One binning rule across vendors and nodes."],
             "visual": "margin_half:margin-cq",
             "sub": ("Beyond the datasheet", "A speed grade covers the worst chip in the bin. Measured margin places each of your chips."),
             "cta": ("Read the margin explainer", "/blog/the-fpga-margin-problem/")},
            {"id": "evidence", "kicker": "Acceptance Evidence", "title": "A record from the first day to the last.",
             "bullets": ["A signed-off timing report per card at acceptance.",
                         "The same measurement repeated in production and at exit.",
                         "Evidence for warranty claims and vendor feedback.",
                         "A history that supports resale, reuse or retirement."],
             "visual": "aging_c:aging-cq",
             "sub": ("Characterization brackets service", "Once on the way in, continuously in production, once on the way out."),
             "cta": ("Lifecycle and second life", "/solutions/lifecycle-second-life/")},
        ],
        "resources": ["margin", "readonly", "brief"],
        "faq": [
            ("Is characterization destructive or slow?", "Neither. A full sweep takes about a second at operating speed. Nothing is written to your design and no operating point changes."),
            ("Do we need a special test rig?", "No. Characterization runs on the card in staging, with the same health layer used in production."),
            ("What does the report contain?", "Measured slack per logic element, the weakest elements, the variation pattern across the chip, and a margin figure for the card at its operating point."),
            ("Can we characterize cards already in service?", "Yes. The same measurement runs in production with no downtime, so deployed cards get a baseline on their first sweep."),
            ("Which devices are supported?", "AMD 7-series, UltraScale and UltraScale+ today, with select Altera Agilex 7 devices; more families in development. See device support."),
            ("How does this connect to tuning?", "The report is the starting point for per-chip sign-off. Voltage and frequency scaling are separate, opt-in steps that use the same measurements."),
        ],
    },
    {
        "slug": "lifecycle-second-life", "problem": ('Boards retired on age, not condition', 'Healthy boards come out on a schedule while marginal ones stay in. Keep each board in service on its measured slack and retire the rest on evidence.'), "name": "Lifecycle & Second Life", "icon": "clock",
        "short": "Keep healthy boards in service. Retire the rest on evidence.",
        "lead": "Cards run six years and longer, past what vendors planned for. Fluid Silicon shows which cards can stay, when the rest will need attention, and what a card leaving service is worth.",
        "impact": [("6+ years", "cards now stay in production"),
                   ("5", "board generations one operator keeps in deployment at once (Rydberg et al., FPGA 2026)"),
                   ("1 s", "to characterize a card on its way out")],
        "apps": [
            ("extend", "clock", "Service-Life Extension", "Cards kept in service on measured health, not age."),
            ("plan", "calendar", "Replacement Planning", "A replacement date per card for capacity and budget planning."),
            ("exit", "doc", "Exit Characterization", "A measured record of every card leaving service."),
            ("second", "layers", "Resale, Reuse or Retire", "The next step for each card, with the data behind it."),
        ],
        "dives": [
            {"id": "extend", "kicker": "Service-Life Extension", "title": "Retire cards because they are failing, not because they are old.",
             "bullets": ["An aging curve per card from its temperature history.",
                         "Cards inside their margin kept in service, with evidence.",
                         "Operating points lowered where that buys years, in your windows.",
                         "Repair instead of replacement where your policy allows."],
             "visual": "aging_c:aging-lc",
             "sub": ("Beyond the vendor's plan", "Cards now run six years and more in production. Per-card measurement is what makes that safe."),
             "cta": ("Request a demo", "/demo/")},
            {"id": "plan", "kicker": "Replacement Planning", "title": "A replacement date per card, not a fleet average.",
             "bullets": ["Time-to-threshold for every card, updated with every sweep.",
                         "Capacity planning from measured health.",
                         "Budgets timed to when cards will need attention.",
                         "Outliers surfaced early."],
             "visual": "mock_light:fleet|Fleet view ranked by time to threshold. Illustrative screen.",
             "sub": ("Plans on evidence", "Maintenance planned around guesses costs capacity and spare hardware held in reserve."),
             "cta": ("Read the aging explainer", "/blog/aging-is-measurable/")},
            {"id": "exit", "kicker": "Exit Characterization", "title": "Measure it on the way out.",
             "bullets": ["Every LUT and carry block measured again at exit.",
                         "The same report as at incoming, so the two compare directly.",
                         "Evidence for warranty claims and vendor feedback.",
                         "A record that travels with the card."],
             "visual": "illus:illus-lc",
             "sub": ("Characterization brackets service", "Once on the way in, continuously in production, once on the way out."),
             "cta": ("Card qualification", "/solutions/card-qualification/")},
            {"id": "second", "kicker": "Resale, Reuse or Retire", "title": "What a used card is worth.",
             "bullets": ["Measured margin and aging history support a resale price.",
                         "Cards with healthy margin redeployed to less critical roles.",
                         "Cards near the threshold retired before they fail elsewhere.",
                         "Sustainability reporting from measured extension, not estimates."],
             "visual": "margin_half:margin-lc",
             "sub": ("The energy behind margin", "Running every chip as if it were the worst one costs energy on every card, every year. Measurement is where the sustainability case starts."),
             "cta": ("Technical brief (PDF)", "/assets/docs/fluid-silicon-technical-brief.pdf")},
        ],
        "resources": ["aging", "generations", "power"],
        "faq": [
            ("How much longer can cards stay in service?", "As long as their measured margin supports it. The aging model gives each card a time-to-threshold; cards inside their margin stay, cards approaching it are planned for."),
            ("Is extending service life safe?", "Every card is measured about once a second for its whole life, and the operating point can be lowered where that buys years. Nothing rests on the card's age or a vendor's worst case."),
            ("What does exit characterization give us?", "A measured record of the card at the end of service, comparable with its incoming report: evidence for resale, reuse, warranty and vendor feedback."),
            ("Does this help with sustainability reporting?", "Yes. Extension and energy savings are measured per card rather than estimated."),
            ("Which devices are supported?", "AMD 7-series, UltraScale and UltraScale+ today, with select Altera Agilex 7 devices; more families in development. See device support."),
            ("Can we start with retirement decisions only?", "Yes. Monitoring and modeling are read-only, and the time-to-threshold alone is enough to plan replacements. Tuning and repair are separate, opt-in steps."),
        ],
    },
    {
        "slug": "power-performance", "problem": ('Guardbands cost energy and performance', 'Variation and latent defects force every device onto a guardband sized for the slowest silicon at the worst-case corner. Once each device is monitored, the excess is recovered within its measured margin, never past it.'), "name": "Guardband Recovery", "icon": "power",
        "short": "Excess guardband recovered as energy and performance, within each device's measured margin.",
        "lead": "Guardbands are set once, for the slowest silicon at the worst-case corner, because that is the only device a vendor can guarantee. Once every device is monitored in-system and its defects are exposed, Fluid Silicon recovers the excess guardband as lower power and, where a workload needs it, performance. Reliability comes first: the margin you specify stays in place, and nothing runs past what the measurement supports.",
        "impact": [("30–54%", "timing margin carried today for the worst-case corner*"),
                   ("< 20 ps", "per-link resolution; the margin you keep covers measurement error plus drift"),
                   ("1 s", "to re-measure every logic element after a change")],
        "apps": [
            ("avs", "power", "Adaptive Voltage Scaling", "Vccint set to what each device's measured timing needs, with your margin kept in place."),
            ("afs", "bolt", "Adaptive Frequency Scaling", "The clock held inside each device's measured margin, and lowered as the device ages."),
            ("signoff", "check", "Per-Device Sign-off", "A margin measured on each device and each link, in place of the worst-case guardband."),
            ("policy", "tune", "Operating-Point Policy", "Operating points coordinated per device, per board or fleet-wide, in your windows."),
        ],
        "dives": [
            {"id": "avs", "kicker": "Adaptive Voltage Scaling", "title": "Lower power without giving up margin.",
             "bullets": ["Vccint set from timing measured on that device, not a family datasheet.",
                         "Margin held for measurement error and drift until the next sweep; each link is resolved to under 20 ps.",
                         "Every change scheduled, handshake-gated and re-measured within a second.",
                         "One policy on AMD and Altera devices.",
                         "Read-only first: the recommended operating point is visible before anything moves."],
             "visual": "mock_light:tune|One card's recommended operating point, waiting for approval. Illustrative screen.",
             "sub": ("Worked example", "10,000 cards at 75 W in a facility with a PUE of 1.2: every 1% of card power is about 79 MWh a year at the wall. The reduction available depends on the margin your devices carry today."),
             "cta": ("Request a demo", "/demo/")},
            {"id": "afs", "kicker": "Adaptive Frequency Scaling", "title": "The clock follows measured margin.",
             "bullets": ["Sustainable clock measured per device over long periods, not a one-time lab figure.",
                         "Aging models lower the clock before a device drifts out of margin.",
                         "Any increase is opt-in, in your maintenance windows, with a handshake on every device.",
                         "Monitoring continues after every change."],
             "visual": "margin_half:margin-pp",
             "sub": ("Guardrails", "The clock moves only inside measured margin, and only by the amount that leaves your specified slack in place. A device aging toward its threshold is brought down before it reaches it."),
             "cta": ("Technical brief (PDF)", "/assets/docs/fluid-silicon-technical-brief.pdf")},
            {"id": "signoff", "kicker": "Per-Device Sign-off", "title": "One margin per device.",
             "bullets": ["Each device's path-delay distribution, measured link by link.",
                         "Sign-off margin: measurement error plus drift, with each link resolved to under 20 ps.",
                         "Measuring more devices finds more tails; it adds no margin to the devices without them.",
                         "The same sign-off from 28 nm to 10 nm class."],
             "visual": "illus:illus-pp",
             "sub": ("Why every device carries margin today", "A vendor must guarantee timing for every device it ships, so its model describes the worst one: defective, hot, at elevated voltage, at end of life. That is the right call for a vendor. It also means every device you run carries that one's guardband."),
             "cta": ("Read the margin explainer", "/blog/the-fpga-margin-problem/")},
            {"id": "policy", "kicker": "Operating-Point Policy", "title": "One device, one board or the whole fleet.",
             "bullets": ["Operating points coordinated per device, per board or fleet-wide.",
                         "Your thresholds, your windows, your approvals.",
                         "Telemetry in one vendor-neutral schema, into your existing monitoring.",
                         "Nothing is applied without a handshake."],
             "visual": "illus:illus-pp-policy",
             "sub": ("Read-only first", "Monitoring and modeling never change an operating point. Voltage and frequency scaling are separate steps enabled by policy, and you can stop at any step."),
             "cta": ("How adoption works", "/blog/read-only-first/")},
        ],
        "resources": ["power", "margin", "brief"],
        "faq": [
            ("Is this overclocking?", "No. The goal is reliability. Every device is kept inside the timing margin measured on that device, with your specified slack in place, and the operating point is pulled back as it ages. Energy and performance are what the worst-case guardband no longer has to hold back."),
            ("How much power can we save?", "It depends on the margin each device carries today, which we measure before recommending anything. The worked example shows the arithmetic; an evaluation on a few of your boards shows your number."),
            ("Does tuning put timing at risk?", "Margin is kept for measurement error plus drift, every change is re-measured within a second, and aging models pull the operating point back before a device drifts toward the threshold. Every change is scheduled and handshake-gated."),
            ("Can we run voltage and frequency scaling together?", "Yes. Both read the same measurements. Most deployments start with voltage, which lowers power without changing throughput, and change frequency only where a workload needs it and the measured margin allows."),
            ("Which devices are supported?", "AMD 7-series, UltraScale and UltraScale+ today, with select Altera Agilex 7 devices. Stratix 10, Arria 10 and Versal AI Core are in development. See device support."),
            ("Does it change our design?", "Your RTL is not changed. The health layer occupies a small region reserved beside your design, planned with your team during evaluation, and needs no JTAG exposure."),
            ("What does it cost in area and delay?", "Under 1% of LUTs and under 5% of flip-flops on a production shell, under 2% delay impact, and no downtime to monitor."),
            ("How does this relate to facility energy?", "Card power is paid for again in cooling and distribution, which is what PUE captures. Whatever you save on the card is multiplied at the wall."),
            ("Is the margin you sign off the margin we keep?", "Yes. The measurement made at qualification continues in production, so the margin is checked for the life of the device rather than assumed once."),
        ],
    },
    {
        "slug": "fleet-operations", "problem": ('No common health metric across platforms', 'AMD and Altera devices across several nodes and board generations report health differently, if at all. One metric covers all of them: measured slack as a share of the clock period.'), "name": "Fleet Deployment & Operations", "icon": "rack",
        "short": "One health metric across every vendor, node and board generation.",
        "lead": "Mixed vendors, mixed nodes, several board generations and strict change control. Fluid Silicon gives every card the same health metric, the same telemetry and the same rules for change.",
        "impact": [("2", "vendors on one platform: AMD and Altera"),
                   ("28–10 nm", "process nodes supported today; 14 nm and 7 nm families in development"),
                   ("< 5%", "of flip-flops, and under 1% of LUTs, on a production shell")],
        "apps": [
            ("deploy", "layers", "Deployment & Integration", "A small reserved region beside your design, on your site. No RTL changes, no JTAG exposure."),
            ("telemetry", "monitor", "Vendor-Neutral Telemetry", "One schema, one metric, one set of thresholds on every family."),
            ("changes", "calendar", "Scheduled, Handshake-Gated Changes", "Tuning and repair in your windows, per device, per server or fleet-wide."),
            ("dashboards", "doc", "Fleet Dashboards & Reports", "Healthy, watch and action counts, time-to-threshold and capacity reports."),
        ],
        "dives": [
            {"id": "deploy", "kicker": "Deployment & Integration", "title": "Built for designs already in production.",
             "bullets": ["Works with any design: your RTL, logic and I/O stay as built.",
                         "Under 1% of LUTs, under 5% of flip-flops, under 2% delay impact.",
                         "No JTAG port exposed on production systems.",
                         "Runs on your site, planned with your team during evaluation."],
             "visual": "illus:illus-fo",
             "sub": ("Six guarantees", "Integrity, access, availability, footprint, control and data. The full list is on the security and integration page."),
             "cta": ("Security and integration", "/technology/security/")},
            {"id": "telemetry", "kicker": "Vendor-Neutral Telemetry", "title": "The same number means the same thing on every part.",
             "bullets": ["Health metric: measured slack as a share of the clock period, per logic-element link.",
                         "One telemetry schema, one set of thresholds, one aging model.",
                         "Vendor-specific integration handled by Fluid Silicon.",
                         "Fits your existing monitoring; nothing leaves your network."],
             "visual": "device_summary:devsum-fo",
             "sub": ("Two layers", "What you see and act on is identical on every vendor. What differs between vendors is handled beneath it."),
             "cta": ("Device support", "/technology/devices/")},
            {"id": "changes", "kicker": "Scheduled, Handshake-Gated Changes", "title": "Change control your operations team will recognize.",
             "bullets": ["Read-only by default; tuning and repair enabled by policy.",
                         "Changes run only in maintenance windows you schedule.",
                         "Coordination per device, per server or fleet-wide.",
                         "A handshake on every action."],
             "visual": "mock_light:card|A recommendation waiting for approval. Illustrative screen.",
             "sub": ("Deterministic changes", "Every change is scheduled, approved and re-measured within a second, so the state of the fleet is always known."),
             "cta": ("How adoption works", "/blog/read-only-first/")},
            {"id": "dashboards", "kicker": "Fleet Dashboards & Reports", "title": "The fleet on one screen, the card on the next.",
             "bullets": ["Healthy, watch and action counts, and the cards that need attention first.",
                         "Median slack across the fleet, and its trend.",
                         "Time-to-threshold for capacity and replacement planning.",
                         "Reports by family, generation, site or vendor."],
             "visual": "mock_light:fleet|Fleet overview. Illustrative screen.",
             "sub": ("Several generations at once", "Large operators keep several board generations in service at the same time. One metric across all of them is what makes a fleet view possible."),
             "cta": ("Read: one health metric, many generations", "/blog/one-health-metric-many-generations/")},
        ],
        "resources": ["generations", "security", "devices"],
        "faq": [
            ("How does it fit our monitoring?", "Telemetry follows one vendor-neutral schema, so it lands in the monitoring you already run. The platform is deployed on your site."),
            ("Do we need to change our design?", "Your RTL is not changed. What integration needs from your team, a small resource reservation beside your design, is planned during evaluation."),
            ("How are changes controlled?", "Read-only is the default. Tuning and repair are enabled separately by policy, run in windows you schedule, and every action is handshake-gated."),
            ("Can we coordinate changes across a rack?", "Yes. Operating points can be coordinated per device, per server or across the fleet."),
            ("Which devices are supported?", "AMD 7-series, UltraScale and UltraScale+ today, with select Altera Agilex 7 devices. Stratix 10, Arria 10 and Versal AI Core are in development."),
            ("What about cards from two vendors in the same rack?", "They report the same metric, the same schema and the same thresholds. That is the point of the vendor-neutral layer."),
        ],
    },
]

SOL = {s["slug"]: s for s in SOLUTIONS}

# ------------------------------------------------------------------ industries
INDUSTRIES = [
    {
        "slug": "board-system-makers", "name": "Board & System Makers", "icon": "layers", "art": "factory",
        "short": "Ship cards with measured margin and a health signal for the life of the board.",
        "lead": "Every card you ship carries the vendor's worst-case margin, because until now there was no way to measure each one. Characterize every card before it leaves, show what it sustains, and give customers a health signal for the life of the board.",
        "stats": [("> 20%", "random variation between chips at 16, 14 and 7 nm"), ("1 s", "to characterize a card"), ("< 1%", "of LUTs for the health layer")],
        "pillars": [("chip", "Ship what you measured", "A timing and variation report per card, not a datasheet corner."),
                    ("shield", "Fewer field returns", "Tail cards found at incoming, before they fail at a customer."),
                    ("bolt", "A differentiated product", "Cards that carry their own health metric for the life of the board."),
                    ("doc", "Feedback to the silicon vendor", "Measured evidence for yield, warranty and supply conversations.")],
        "modules": ["card-qualification", "power-performance", "reliability-availability-serviceability", "failure-prediction-diagnostics", "lifecycle-second-life"],
        "quotes": [],
        "resources": ["margin", "readonly", "brief"],
    },
    {
        "slug": "aerospace-defense", "name": "Aerospace & Defense", "icon": "satellite", "art": "satellite",
        "short": "Far-edge systems with tight power budgets and no service access.",
        "lead": "Satellites, aircraft, radar and remote ground stations hold FPGAs to strict reliability bounds under tight power budgets, often with no chance of service. Fluid Silicon starts before deployment, with a per-element qualification of every board, then lets fielded systems watch their own timing health and plan around degradation. Tuning and repair come later, and only where the program's configuration control allows.",
        "stats": [("0", "changes to a fielded design until you approve one"), ("< 1%", "of LUTs for self-monitoring"), ("1 s", "to check every logic element in the field")],
        "pillars": [("check", "Qualification first", "Every board characterized per element before it ships, with weak resources mapped and spares identified."),
                    ("monitor", "Read-only monitoring", "The fielded system checks its own logic at speed while it runs; nothing changes without approval."),
                    ("model", "Aging prediction", "A time-to-threshold per board, from its own temperature history, for planning replacements and mission life."),
                    ("shield", "Clear about scope", "Complements radiation mitigation such as scrubbing and redundancy; does not replace it. Tuning and repair only where configuration control allows.")],
        "modules": ["card-qualification", "reliability-availability-serviceability", "failure-prediction-diagnostics", "lifecycle-second-life", "power-performance"],
        "quotes": [],
        "resources": ["aging", "security", "brief"],
    },
    {
        "slug": "telecommunications", "name": "Telecommunications", "icon": "tower", "art": "tower",
        "short": "A decade in cabinets that are rarely visited.",
        "lead": "Base stations, edge sites and network appliances run FPGAs for a decade in cabinets that are rarely visited. Timing health turns unplanned site visits into scheduled maintenance.",
        "stats": [("6+ years", "cards in service, and longer at the edge"), ("1 s", "to measure every logic element"), ("0", "downtime to monitor")],
        "pillars": [("tower", "Fewer site visits", "A forecast per board, so a visit fixes what is about to fail."),
                    ("calendar", "Planned replacement", "Time-to-threshold feeds the maintenance schedule instead of an outage."),
                    ("power", "Power at the edge", "Voltage trimmed to measured need on sites with tight power and cooling."),
                    ("layers", "Multi-generation fleets", "One health metric across every vendor and board generation deployed.")],
        "modules": ["reliability-availability-serviceability", "lifecycle-second-life", "power-performance", "failure-prediction-diagnostics", "fleet-operations"],
        "quotes": [],
        "resources": ["aging", "generations", "brief"],
    },
    {
        "slug": "test-measurement", "name": "Test & Measurement", "icon": "thermo", "art": "bench",
        "short": "Instruments whose timing has to stay exactly what it was.",
        "lead": "Instruments depend on FPGA timing staying what it was when the product shipped. Measure it continuously, and know the moment it isn't.",
        "stats": [("< 20 ps", "per-link measurement precision"), ("1 s", "to measure every logic element"), ("< 2%", "delay impact on your design")],
        "pillars": [("check", "Measurement integrity", "Timing health measured at the source, on every logic element."),
                    ("variation", "Drift detection", "A slack history per element, so drift is seen before it reaches a result."),
                    ("clock", "Long product lives", "Instruments stay in service for a decade; the health layer stays with them."),
                    ("doc", "Evidence for support", "A measured record that shortens the path from a customer report to a cause.")],
        "modules": ["failure-prediction-diagnostics", "reliability-availability-serviceability", "card-qualification", "lifecycle-second-life", "power-performance"],
        "quotes": [],
        "resources": ["aging", "margin", "brief"],
    },
    {
        "slug": "ai-hpc", "name": "AI / HPC", "icon": "bolt", "art": "accelerators",
        "short": "Hot, high-utilization clusters where every watt and every timing fault counts.",
        "lead": "Accelerator clusters run hot, at high utilization, for years. FPGAs in the data path must hold timing under those conditions, and every watt they save goes to the accelerators.",
        "stats": [("30–54%", "timing margin a chip carries today*"), ("< 2%", "delay impact of the health layer"), ("1 s", "to measure every logic element")],
        "pillars": [("bolt", "Sustained performance", "The clock each chip can hold for long periods, measured rather than assumed."),
                    ("power", "Power for compute", "Voltage trimmed on the FPGAs so the budget goes to the accelerators."),
                    ("search", "Timing faults caught early", "A weakening element found before it produces a wrong answer."),
                    ("rack", "Cluster-wide view", "One health metric across every card, vendor and generation.")],
        "modules": ["power-performance", "reliability-availability-serviceability", "failure-prediction-diagnostics", "fleet-operations", "card-qualification"],
        "quotes": ["fpga26"],
        "resources": ["power", "aging", "brief"],
    },
    {
        "slug": "data-center-cloud", "name": "Data Center & Cloud", "icon": "rack", "art": "racks",
        "short": "Multi-vendor fleets, several board generations, years in service.",
        "lead": "FPGAs are infrastructure: SmartNICs, accelerators and network functions across vendors and board generations. At that scale, one unexpected failure does not stay contained.",
        "stats": [("> 1M", "Azure hosts with FPGA-based SmartNICs (Firestone et al., NSDI 2018)"), ("5", "board generations in deployment at once (Rydberg et al., FPGA 2026)"), ("6+ years", "cards in service")],
        "pillars": [("shield", "Hardware reliability", "A failing chip caught before it removes capacity or sends errors downstream."),
                    ("power", "Power efficiency", "Each card's voltage trimmed to what its measured timing needs."),
                    ("clock", "Capex deferral", "Healthy cards kept in service on evidence; replacements planned before outages."),
                    ("doc", "Vendor feedback", "Per-element evidence for returns, warranty and supply decisions.")],
        "modules": ["reliability-availability-serviceability", "power-performance", "card-qualification", "fleet-operations", "lifecycle-second-life"],
        "quotes": ["fpga26", "nsdi"],
        "resources": ["generations", "power", "brief"],
    },
]

IND = {i["slug"]: i for i in INDUSTRIES}

# what each solution does for an industry: four bullets, used on every industry page
MODULE_BULLETS = {
    "card-qualification": ["Every card measured at speed before it enters service.", "Tail cards found at incoming, not in the field.", "A per-card timing and variation report, read-only.", "Weak-resource maps for your next build."],
    "power-performance": ["Voltage trimmed to what each chip's measured timing needs.", "Frequency raised where measured margin supports it.", "Margin kept only for measurement error plus drift; each link resolved to under 20 ps.", "Changes scheduled, handshake-gated and re-measured."],
    "reliability-availability-serviceability": ["Every logic element swept about once a second, with no downtime.", "A time-to-threshold per card from its own temperature history.", "Alerts on your thresholds, actions in your windows.", "Where an element degrades, only that path is moved, through your change process."],
    "failure-prediction-diagnostics": ["A forecast per card and per element.", "Errors tied to the logic that caused them.", "Outliers surfaced before they fail.", "Per-element history for root cause and vendor feedback."],
    "fleet-operations": ["One health metric on AMD and Altera parts.", "One telemetry schema into your existing monitoring.", "Read-only by default; changes by policy, in your windows.", "Dashboards and reports by family, generation, site or vendor."],
    "lifecycle-second-life": ["Cards kept in service on measured health, not age.", "A replacement date per card for capacity and budget planning.", "Exit characterization when a card leaves service.", "Evidence for resale, reuse or retirement."],
}

# ------------------------------------------------------------------ technology page
TECH_PILLARS = [
    ("monitoring", "monitor", "Timing Health Monitoring", "Per-element timing measured at speed, on the chip, while your design runs."),
    ("integration", "layers", "Integration & Deployment", "A small reserved region beside your design, deployed on your site."),
    ("characterization", "check", "Characterization Applications", "Every card measured before service and on the way out."),
    ("in-field", "tune", "In-Field Applications", "Monitor, model, tune and, when needed, repair, for the life of every card."),
]

TECH_FAQ = [
    ("What does the health layer measure?", "Timing slack on individual logic elements, including LUTs, carry blocks and the links between them, at operating speed. A full sweep of every element takes about a second, with each link resolved to under 20 ps."),
    ("Does it change our design?", "Your RTL is not changed. The health layer occupies a small region reserved beside your design, sized and placed with your team during evaluation. Your logic, routing and I/O stay as built. Repair, if you enable it, moves only a path whose element is degrading; everything else stays put."),
    ("What does it cost in resources?", "Under 1% of LUTs and under 5% of flip-flops on a production shell, with under 2% delay impact."),
    ("Which devices and toolchains?", "AMD 7-series, UltraScale and UltraScale+ today, with select Altera Agilex 7 devices. Integration with each vendor's toolchain, including AMD Vivado and Altera Quartus, is handled by Fluid Silicon."),
    ("Does it cover the whole lifecycle?", "Yes. Characterization at incoming, continuous monitoring in production, and characterization again at exit. Tuning and repair are opt-in steps in between."),
    ("How is it different from monitoring built into an ASIC?", "Monitoring designed into an ASIC has to be there at tape-out. FPGAs are programmable, so the health layer is added beside a design already in your racks, with no new silicon and no RTL changes. FPGAs are where we start; the same approach extends to other reconfigurable and programmable silicon."),
    ("Is it secure?", "The platform runs on your site. No JTAG port has to be exposed, nothing is written into your design's logic, telemetry stays in your network in one schema you control, and every action is opt-in, scheduled and handshake-gated. See security and integration."),
    ("How does the sensing work?", "Sensor architecture, deployment mechanics and calibration methods are shared with evaluation partners under NDA. Ask for a technical session."),
]

# ------------------------------------------------------------------ careers
VALUES = [
    ("monitor", "Measure first", "A number measured on real silicon settles an argument. We build the instrument before the opinion."),
    ("shield", "Earn trust", "Nothing changes on a production system without the operator's approval. We design accordingly."),
    ("layers", "Own the whole stack", "From logic elements to fleet dashboards. Every hire owns real parts of it."),
    ("bolt", "Ship, then measure again", "A small team, real boards on the bench, results that show up in production."),
]

BENEFITS = [
    ("chip", "Real silicon", "Boards on the bench, measurements from real chips, problems no textbook has solved."),
    ("doc", "Real ownership", "A small team means your work ships with your name on it."),
    ("model", "Growth", "Work across hardware, software and customers, with a mentor and a defined project from day one."),
]

JOBS = [
    {"title": "FPGA Engineer", "dept": "Hardware", "type": "Full-time", "loc": "Philadelphia, PA", "path": "/jobs/#fpga-engineer"},
    {"title": "Systems Software Engineer, HW/SW Co-Design", "dept": "Software", "type": "Full-time", "loc": "Philadelphia, PA", "path": "/jobs/#systems-software-engineer"},
    {"title": "Software Engineering Intern", "dept": "Software", "type": "Internship", "loc": "Philadelphia, PA", "path": "/jobs/#swe"},
    {"title": "Hardware Design (FPGA) Intern", "dept": "Hardware", "type": "Internship", "loc": "Philadelphia, PA", "path": "/jobs/#hde"},
    {"title": "Business Development Intern", "dept": "Business", "type": "Internship", "loc": "Philadelphia, PA", "path": "/jobs/#bd"},
]

# ------------------------------------------------------------------ team (company page and home)
TEAM = [
    {"slug": "nhlanhla-mavuso", "name": "Nhlanhla Mavuso", "role": "Co-Founder and CEO",
     "bio": "Nhlanhla developed the approach behind Fluid Silicon through master's research at the University of Pennsylvania on online health monitoring and runtime repair for commercial FPGAs.",
     "creds": ["BA Physics, Penn 2026", "BSE Computer Engineering, Penn 2026", "MSE Electrical Engineering, Penn 2026", "VIPER Class of 2026", "President's Sustainability Prize, 2026"],
     "links": [("linkedin", "https://www.linkedin.com/in/nmavuso/")]},
    {"slug": "andre-dehon", "name": "Dr. André DeHon", "role": "Co-Founder and Chief Scientific Advisor",
     "bio": "André has worked in reconfigurable computing for decades, at Berkeley, Caltech and, since 2006, the University of Pennsylvania, where he is the Oliver C. Boileau Jr. and Nan Eleze Boileau Professor of Electrical Engineering. His research on FPGA architecture and interconnect underpins Fluid Silicon's approach.",
     "creds": ["SB, SM, PhD, MIT", "ACM Fellow", "IEEE Fellow", "NAI Fellow", "10 papers in the TCFPGA Hall of Fame", "Chair, ACM SIGDA TC on FPGAs"],
     "links": [("scholar", "https://scholar.google.com/citations?user=nintPk8AAAAJ"), ("penn", "https://directory.engineering.upenn.edu/andre-dehon/")]},
]

PRIZE_QUOTE = ("Fluid Silicon's adaptive approach to chip performance exemplifies Penn's strength in applied innovation and offers a scalable path to greater efficiency and sustainability.",
               "J. Larry Jameson, President, University of Pennsylvania")

# ------------------------------------------------------------------ why now (home page; figures from the margin and aging posts)
WHYNOW = [
    ("> 20%", "Variation is a first-order constraint", "At 16, 14 and 7 nm, random variation alone exceeds 20%, on top of systematic variation and latent defects across the die. Two devices with the same part number and speed grade are less alike with every node.", "/blog/the-fpga-margin-problem/"),
    ("6+ years", "Devices outlive their timing models", "Boards stay in service for six years and more, and a device in a hot enclosure ages faster than the same part in a cool one. Sign-off happens once; the silicon keeps changing.", "/blog/aging-is-measurable/"),
    ("Per device", "In-system measurement is now practical", "FPGAs are reprogrammable after they ship, so a health layer can be added to devices already in service, with no new silicon. Each device's margin is measured instead of assumed from the slowest one.", "/technology/"),
]

# ------------------------------------------------------------------ culture (careers page)
CULTURE = [
    ("flag", "Raise it the day you see it", "Problems get raised early and the person who raised them gets thanked. Mistakes are examined openly, as information about the system, not the person."),
    ("monitor", "Measure before claiming", "A number measured on real silicon settles an argument. We hold ourselves to a high standard and we show our work."),
    ("shield", "Tell the truth early", "To each other and to customers. Hardware people can trust is built by people who can be trusted."),
    ("layers", "A close team with shared stakes", "Not a family: a team. Everyone owns real parts of the product, plans for intensity and recovers from it, and leaves better than they arrived."),
]
